Removed some stuff related to filename suffixes.

diff --git a/inf4 b/inf4
--- a/inf4
+++ b/inf4
@@ -84,7 +84,7 @@ function main.cmd () {
       item.fetch )
         $cmd $@;
         ;;
-      metadata | file.is_metadata | metadata_file ) # Metadata Commands
+      file.metadata | file.is_metadata | file.metadata_file ) # Metadata Commands
         $cmd $@;
         ;;
       add | put ) # Update Commands
@@ -120,9 +120,9 @@ inf4 --base=https://foo.com/fcrepo/rest/bar \
      --prefix=baz:https://baz.org/schema config
 Will write a new configuration file with the base and prefix set.
 =cut
-function metadata() {
+function file.metadata() {
   local opts=`getopt -o @:atM:u --long file:,auto:,type:,no-metadata,mime-type:,update -n 'inf4 put' -- "$@"`
-  if [ $? != 0 ] ; then err 1 "Bad inf4 metadata options."; fi
+  if [ $? != 0 ] ; then err 1 "Bad inf4 file.metadata options."; fi
   eval set -- "$opts"
   metadata_opts $@
 }
@@ -164,7 +164,7 @@ function metadata_opts() {
 
 #  declare -a types=('ldp:NonRDFSource');
 
-  metadata=$(metadata_file --quiet --exists $file)
+  metadata=$(file.metadata_file --quiet --exists $file)
   if [[ -n $metadata ]]; then
     cat $metadata;
     exit 0
@@ -239,34 +239,27 @@ inf4 [inf4options] file.is_metadata file
 
 Returns true if the passed file is a metadata file, false if not. The file
 undergoes two tests. First it is validated as a metadata file type, based on the
-FILE and DIR metadata file patterns. If the file matches the pattern, then the
+metadata file patterns (metadata.file in YML file). If the file matches the pattern, then the
 associated file is checked for existance. If the file exists, then we assume the
 file is a metadata file associated with the appropriate file or directory.
 Can be used like C<if (inf4 file.is_metadata foo.png.ttl); then echo metadata; fi>.
 
 =cut
 function file.is_metadata() {
-  local file_pattern='^(.*)\.ttl$'
-  local dir_metadata='^index.ttl$'
-  if [[ $(basename $1) =~ ${dir_metadata} && -d $(dirname $1) ]]; then
+  local file_pattern=${INF4[metadata_pattern]}
+  if [[ $1 =~ ${file_pattern} && -f ${BASH_REMATCH[1]} ]]; then
     exit 0;
-  elif [[ $1 =~ ${file_pattern} ]]; then
-    if [[ -f ${BASH_REMATCH[1]} ]]; then
-      exit 0;
-    fi
   else
     exit 1;
-  fi
 }
 
-function metadata_file() {
-    local opts=`getopt -o qx --long quiet,exists -n 'metadata_file' -- "$@"`
+function file.metadata_file() {
+    local opts=`getopt -o qx --long quiet,exists -n 'file.metadata_file' -- "$@"`
     if [[ $? != 0 ]] ; then return ; fi
 
     eval set -- "$opts"
 
-    local file_pattern='FILE.ttl';
-    local dir_pattern='DIR/index.ttl';
+    local mf=${INF4[metadata_file]};
     local ttl;
     local exists=;
     local quiet=
@@ -285,19 +278,17 @@ function metadata_file() {
       err $quiet 1 "$1 not found"
     fi
 
+    if (file.ignore $1); then
+      err $quiet "$1 file.ignore"
+    fi
     if (file.is_metadata $1) ; then
-      err $quiet 1 "$1 is a metadata file"
+      err $quiet "$1 file.is_metadata"
     fi
 
-    if [[ -f $1 ]] ; then
-      ttl=${file_pattern//FILE/$1}
+    if [[ -f $1 || -d $1 ]] ; then
+      ttl=${mf//FILE/$1}
       if [[ -n $exists && ! -f $ttl ]]; then
-        err 1 "$ttl not found"
-      fi
-    elif [[ -d $1 ]] ; then
-      ttl=${dir_pattern//DIR/$1}
-      if [[ -n $exists && ! -f $ttl ]]; then
-        err $quiet 1 "$ttl not found"
+        err $quiet "$ttl not found"
       fi
     fi;
     echo $ttl
@@ -335,14 +326,12 @@ function file.path() {
     err 1 "$1 file.is_metadata"
   fi
 
-  local filename=$(basename $1)
-  if [[ -n $full ]]; then
-    filename=${filename//./_}
-  else
-    filename=${filename//.*/}
-  fi
-  local dirname=$(dirname $(realpath --relative-to=${INF4[home]} $1))
-  echo $dirname/$filename;
+#  local filename=$(basename $1)
+#  local dirname=$(dirname $(realpath --relative-to=${INF4[home]} $1))
+#  echo $dirname/$filename;
+
+  local path=$(realpath --relative-to=${INF4[home]} $1)
+  echo $path
 }
 
 ldp_path() {
@@ -530,7 +519,7 @@ function add() {
     for i in $@; do
       if ! (file.ignore $i) ; then
         # Save files, check ldp.path
-        if ! ( is_metadata_file $i) && [[ -f $i ]]; then
+        if ! ( file.is_metadata $i) && [[ -f $i ]]; then
           local fn=$(ldp.path $i);
           #log "F->FN $i->$fn"
           if [[ ${file_for[$fn]} ]] ; then
