ACL updates.

diff --git a/inf4 b/inf4
--- a/inf4
+++ b/inf4
@@ -27,16 +27,18 @@ function err() {
 
 function _http () {
   local stdinp=
-  if [[ $1 == '-n' ]]; then
+  local http="http --ssl=${INF4[http_ssl]} --session=${INF4[http_session]}"
+  if [[ $1 == '-n' || -n ${INF4[noop]} ]]; then
+    shift
     if [[ ! -t 0 ]]; then
       IFS='' read -r -d '' stdinp;
-      log "http --print=${INF4[http_print]} $@ <<<'$stdinp'"
+      log "$http $@ <<<'$stdinp'"
     else
-      log "http --print=${INF4[http_print]} $@"
+      log "$http $@"
     fi
   else
-    log http $@
-    http $@
+    log $http $@
+    $http $@
   fi
 }
 
@@ -87,7 +89,10 @@ function main.cmd () {
       file.metadata | file.is_metadata | file.metadata_file ) # Metadata Commands
         $cmd $@;
         ;;
-      add | put ) # Update Commands
+      collection.create  | collection.delete | collection.upload )
+        $cmd $@;
+        ;;
+      put ) # Update Commands
         $cmd $@;
         ;;
 #	    cd | pwd | pushd | popd ) # Directory Commands
@@ -121,42 +126,29 @@ inf4 --base=https://foo.com/fcrepo/rest/bar \
 Will write a new configuration file with the base and prefix set.
 =cut
 function file.metadata() {
-  local opts=`getopt -o @:atM:u --long file:,auto:,type:,no-metadata,mime-type:,update -n 'inf4 put' -- "$@"`
+  local opts=`getopt -o axm --long auto,extra:,mime: -n 'inf4 file.metadata' -- "$@"`
   if [ $? != 0 ] ; then err 1 "Bad inf4 file.metadata options."; fi
   eval set -- "$opts"
-  metadata_opts $@
-}
 
-function metadata_opts() {
-  local metadata=
-  local no_metadata=
-  local mime=
-  local name=
-  declare -A types;
-  local file=
-  local update=
+  local metadata
+  local mime
+  local extra
+  declare -a types;
 
   while true; do
     case $1 in
-      -@ | --file ) # Used for mime-types
-        file=$2;
-        shift 2;;
       -a | --auto)
         auto=1;
         shift;
         ;;
-	    -M | --no-metadata)
-        no_metadata=1;
-        shift;
-		    ;;
-	    -m | --mime-type)
-        mime=$2; shift 2;;
-      -t | --type)
-        types+=($2);
-        shift 2;;
-      -u | --update)
-        update=1;
-        shift;;
+      -m | --mime)
+        mime=$2;
+        shift 2;
+        ;;
+      -x | --extra)
+        extra=$2;
+        shift 2;
+        ;;
 	  	--) shift; break;;
     	*) break;;
     esac
@@ -164,19 +156,24 @@ function metadata_opts() {
 
 #  declare -a types=('ldp:NonRDFSource');
 
-  metadata=$(file.metadata_file --quiet --exists $file)
+  metadata=$(file.metadata_file --quiet --exists $1)
   if [[ -n $metadata ]]; then
     cat $metadata;
     exit 0
   fi
 
-  local basename=$(basename $file);
+  if [[ -z $auto ]]; then
+    exit 0
+  fi
+
+  local basename=$(basename $1);
 
   if [[ -z $mime ]]; then
-    if [[ $file =~ .ttl$ ]] ; then
-      mime=text/turtle
-    elif [[ -n $file ]]; then
-		  mime=$(file --mime-type -b $file);
+    if [[ $1 =~ .ttl$ ]] ; then
+      mime='text/turtle'
+      delcare -p $types
+    elif [[ -n $1 ]]; then
+		  mime=$(file --mime-type -b $1);
 	  fi;
   fi
 
@@ -186,7 +183,7 @@ function metadata_opts() {
 
   local typestr=$(printf "%s," ${types[@]})
 
-  if [[ -z $extra ]]; then
+  if [[ -z $extra && ${#types[@]} > 0 ]]; then
       read -r -d '' metadata <<AUTO;
 @prefix ldp:    <http://www.w3.org/ns/ldp#> .
 @prefix schema: <http://schema.org/> .
@@ -246,11 +243,13 @@ Can be used like C<if (inf4 file.is_metadata foo.png.ttl); then echo metadata; f
 
 =cut
 function file.is_metadata() {
-  local file_pattern=${INF4[metadata_pattern]}
-  if [[ $1 =~ ${file_pattern} && -f ${BASH_REMATCH[1]} ]]; then
+  local file_pattern=${INF4[metadata_is_metadata]}
+#  log "$1 =~ $file_pattern"
+  if [[ $1 =~ ${file_pattern} && ( -f ${BASH_REMATCH[1]} || -d ${BASH_REMATCH[1]} ) ]]; then
     exit 0;
   else
     exit 1;
+  fi
 }
 
 function file.metadata_file() {
@@ -279,16 +278,16 @@ function file.metadata_file() {
     fi
 
     if (file.ignore $1); then
-      err $quiet "$1 file.ignore"
+      err $quiet 1 "$1 file.ignore"
     fi
     if (file.is_metadata $1) ; then
-      err $quiet "$1 file.is_metadata"
+      err $quiet 1 "$1 file.is_metadata"
     fi
 
     if [[ -f $1 || -d $1 ]] ; then
       ttl=${mf//FILE/$1}
       if [[ -n $exists && ! -f $ttl ]]; then
-        err $quiet "$ttl not found"
+        err $quiet 1 "$ttl not found"
       fi
     fi;
     echo $ttl
@@ -299,55 +298,55 @@ function file.metadata_file() {
 =pod
 =head2 file.path
 =head3 USAGE
-inf4 file.path --full <filepath>
+inf4 file.path --relative <filepath>
 =head4
 Returns the LDP path location for the file.  The default is to simply remove
 the suffix from the basename of a file.  With full however, the suffix is retained.
 =cut
 function file.path() {
-  local opts=`getopt -o f --long full -n 'file.path' -- "$@"`
+  local opts=`getopt -o r --long relative -n 'file.path' -- "$@"`
   if [[ $? != 0 ]] ; then return ; fi
 
   eval set -- "$opts"
 
-  local full=
+  local full=1
+  local path
 
   while true; do
 	  case $1 in
-	    -f | --full) full=1;  shift;;
+	    -r | --relative) full=;  shift;;
 	    -- ) shift; break;;
 	    *) shift; break;
     esac
   done
 
-  if (file.ignore $1); then
-    err 1 "$1 file.ignore"
-  elif (file.is_metadata $1); then
-    err 1 "$1 file.is_metadata"
+  if [[ -z $1 ]]; then
+    if [[ -n $full ]]; then
+      path=${INF4[host]}${INF4[base]}/${INF4[collection]}
+    else
+      path=${INF4[collection]}
+    fi
+  else
+    if (file.ignore $1); then
+      err 1 "$1 file.ignore"
+    elif (file.is_metadata $1); then
+      err 1 "$1 file.is_metadata"
+    fi
+
+    # Special test for collection.ttl
+    if [[ $1 == ${INF4[collection]}.ttl ]]; then
+      path=$(realpath -m --relative-to=${INF4[home]} $1)
+    else
+      path=$(realpath -m --relative-to=${INF4[home]} ${INF4[collection]}/$1)
+    fi
+
+    if [[ -n $full ]]; then
+      path=${INF4[host]}${INF4[base]}/$path
+    fi
   fi
-
-#  local filename=$(basename $1)
-#  local dirname=$(dirname $(realpath --relative-to=${INF4[home]} $1))
-#  echo $dirname/$filename;
-
-  local path=$(realpath --relative-to=${INF4[home]} $1)
   echo $path
 }
 
-ldp_path() {
-  local filename
-  local dirname
-  if [[ $1 = '--full' ]] ; then
-    shift;
-    filename=$(basename $1)
-    filename=${filename//./_}
-  else
-    filename=$(basename $1)
-    filename=${filename//.*/}
-  fi
-  dirname=$(dirname $(realpath --relative-to=${INF4[home]} $1))
-  echo $dirname/$filename
-}
 
 : <<=cut
 =pod
@@ -388,8 +387,8 @@ function item.fetch() {
   local file=$1
   local metadata_file=
 
-  local path=$(ldp.path $file)
-  head=$(_http --print=h HEAD $(url $path))
+  local path=$(file.path $file)
+  head=$(_http --print=h HEAD $(file.path $path))
   eval $(parse_headers "$head")
 
 #  if [[ -n $etag ]]; then
@@ -397,23 +396,21 @@ function item.fetch() {
   if [[ -f $file ]]; then
     echo ${headers[etag]} >> $file.ldp.etag
     # Now get metadata header
-    head=$(_http --print=h HEAD $(url $path)/fcr:metadata)
+    head=$(_http --print=h HEAD $(file.path $path)/fcr:metadata)
     eval $(parse_headers "$head")
     echo ${headers[etag]} >> $file.ldp.ttl.etag
-    _http GET $(url $path)/fcr:metadata prefer:return=minimal Accept:text/turtle > $file.ldp.ttl
+    _http GET $(file.path $path)/fcr:metadata prefer:return=minimal Accept:text/turtle > $file.ldp.ttl
   elif [[ -d $file ]]; then
     echo ${headers[etag]} >> $file/ldp.etag
-    head=$(_http --print=h HEAD $(url $path)/fcr:metadata)
+    head=$(_http --print=h HEAD $(file.path $path)/fcr:metadata)
     eval $(parse_headers "$head")
     echo ${headers[etag]} >> $file/ldp.ttl.etag
-    _http GET $(url $path)/fcr:metadata prefer:return=minimal Accept:text/turtle > $file/ldp.ttl
+    _http GET $(file.path $path)/fcr:metadata prefer:return=minimal Accept:text/turtle > $file/ldp.ttl
   else
     err 1 "item.fetch $file not actionable"
   fi
 
 }
-
-
 
 : <<=cut
 =pod
@@ -423,10 +420,6 @@ inf4 [inf4options] put --auto --mime-type=I<mime> --extra=I<extra> file
 =head4
 Add a file or directory to an LDP.
 =cut
-function url() {
-  echo ${INF4[host]}/$(realpath -m /${INF4[base]}/$1)
-}
-
 function put() {
   local opts=`getopt -o @:atM:u --long file:,auto:,type:,no-metadata,mime-type:,update -n 'inf4 put' -- "$@"`
   if [ $? != 0 ] ; then err 1 "Bad inf4 put options."; fi
@@ -446,7 +439,7 @@ function put() {
         file=$2;
         shift 2;;
       -a | --auto )
-        auto=1;
+        auto=--auto;
         shift;
         ;;
 	    -M | --no-metadata )
@@ -466,37 +459,56 @@ function put() {
     esac
   done
 
+  if [[ -z $file && -z $update ]]; then
+    _http PUT $1
+  fi
+
   if [[ -f $file ]]; then
     if [[ -z $mime ]]; then
       if [[ $file =~ .ttl$ ]] ; then
         mime=text/turtle
+        _http PUT $1 prefer:return=minimal Content-Type:$mime @$file
       else
 		    mime=$(file --mime-type -b $file);
+	      _http PUT $1 Content-Type:$mime @$file
 	    fi;
     fi;
-	  _http -n PUT $(url $1) Content-Type:$mime @$file
   elif [[ -z $update && -d $file ]] ; then
-    _http -n PUT $(url $1)
+    _http PUT $1
   fi
 
   # Now add metadata
   if [[ -z $no_metadata ]]; then
-    eval set -- "$opts"
-    metadata=$(metadata_opts $@ )
-    _http -n  PUT prefer:return=minimal Content-Type:text/turtle $(url $file)/fcr:metadata <<<$metadata
+    metadata=$(file.metadata $auto $file )
+    if [[ -n $metadata ]]; then
+      _http PUT $1/fcr:metadata prefer:return=minimal Content-Type:text/turtle <<<$metadata
+    fi
   fi
+}
+
+
+function collection.create() {
+  _http PUT $(file.path)
+  if [[ -d .acl ]]; then
+    collection.upload .acl
+  fi
+}
+
+function collection.delete() {
+  _http DELETE $(file.path)
+  _http DELETE $(file.path)/fcr:tombstone
 }
 
 : <<=cut
 =pod
-=head2 add
+=head2 collection.upload
 =head3 USAGE
-inf4 [inf4options] add --auto directory
+inf4 [inf4options] collection.upload --auto <files and directories>
 =head4
 Add items to the collection. This will add all files from an item into the system.
 =cut
-function add() {
-  local opts=`getopt -o a --long auto -n 'inf4 add' -- "$@"`
+function collection.upload() {
+  local opts=`getopt -o acd --long auto,create,delete -n 'inf4 collection.upload' -- "$@"`
   if [[ $? != 0 ]] ; then return ; fi
   eval set -- "$opts"
 
@@ -506,52 +518,45 @@ function add() {
   local i;
   declare -a types;
   local auto=
+  local delete=
+  local create=
   declare -A file_for  # [file_for] => filename
 
     while true; do
 	    case $1 in
         -a | --auto ) auto=--auto; shift;;
+        -d | --delete ) delete=--delete; shift;;
+        -c | --create ) create=--create; shift;;
 	      -- ) shift; break;;
 	      *) shift; break;
       esac
     done
 
+    if [[ -n $delete ]]; then
+      collection.delete
+    fi
+
+    if [[ -n $delete || -n $create ]]; then
+      collection.create
+    fi
+
+    local fn
     for i in $@; do
       if ! (file.ignore $i) ; then
-        # Save files, check ldp.path
-        if ! ( file.is_metadata $i) && [[ -f $i ]]; then
-          local fn=$(ldp.path $i);
-          #log "F->FN $i->$fn"
-          if [[ ${file_for[$fn]} ]] ; then
-            # we have name collision, redo
-            local p=${file_for[$fn]}
-            local p_fn=$(ldp.path --full $p)
-            if [[ ${file_for[$p_fn]} ]]; then
-              err 1 "ldp object collision $p_fn: $p and ${file_for[$p_fn]}"
-            else
-              unset file_for[$fn]
-              file_for[$p_fn]=$p;
-            fi
-            fn=$(ldp.path --full $i)
-            if [[ ${file_for[$fn]} ]]; then
-              err 1 "ldp object collision $fn: $i and ${file_for[$fn]}"
-            fi
-          else
+        if ! (file.is_metadata $i); then
+          fn=$(file.path $i);
+          # Save files, check file.path
+          if [[ -f $i ]]; then
             file_for[$fn]=$i;
+          elif [[ -d $i ]]; then
+            i=${i%/}
+            fn=$(file.path $i)
+            put --no-metadata $fn
+            collection.upload $i/*;
+            put --update $auto --file=$i $fn
+          else
+            log "file.unknown $i -- skipping"
           fi
-        elif [[ -d $i ]]; then
-          i=${i%/}
-          fn=$(ldp.path $i)
-          if [[ ${file_for[$fn]} ]]; then
-            err 1 "ldp object collision $fn: $i and ${file_for[$fn]}"
-          fi
-  #        file_for[$fn]=$i;
-          put --no-metadata --file=$i $fn
-          add $i/*;
-          put --update $auto --file=$i $fn
-        else
-          #log "skipping $i"
-          true;
         fi
       fi
     done
@@ -602,7 +607,7 @@ PROMPT
 
   read -p "$prompt" -r token;
 
-  http --print=${INF4[http_print]} --session=${INF4[http_session]} ${INF4[host]}/${INF4[base]} Authorization:"Bearer $token"
+  _http ${INF4[host]}/${INF4[base]} Authorization:"Bearer $token"
 }
 
 : <<=cut
@@ -718,9 +723,9 @@ Quinn Hart <qjhart@ucdavis.edu>
 declare -A INF4;
 declare -A ATTR;
 declare -A IGNORE;
-declare -A OPTS;
+declare -a OPTS;
 
-_home # Verify we are
+_home # Verify we are in a location
 
 # Read the configuration file
 config=${INF4[home]}/.inf4/config.yml
@@ -731,6 +736,7 @@ fi
 _read_attributes
 _read_ignore
 
+
 while true; do
 	case $1 in
 	  -*) OPTS=($1); shift ;;
@@ -740,21 +746,22 @@ while true; do
 done
 
 function init() {
-local opts=`getopt -o h:np: --long base:,dry-run,print: -n 'inf4' -- "$@"`
+  local opts=`getopt -o h:np: --long base:,dry-run,print: -n 'inf4' -- "$@"`
+  if [ $? != 0 ] ; then echo "Bad Command Options." >&2 ; exit 1 ; fi
 
-if [ $? != 0 ] ; then echo "Bad Command Options." >&2 ; exit 1 ; fi
+  eval set -- "$opts"
 
-eval set -- "$opts"
-
-while true; do
-	case $1 in
-	  -n | --dry-run) INF4[noop]=1; shift ;;
-	  -p | --print) INF4[print]=$2; shift 2;;
-	  -- ) shift; break;;
-	  *) break;
-	esac
-done
+  while true; do
+	  case $1 in
+	    -n | --dry-run) INF4[noop]=1; shift ;;
+	    -p | --print) INF4[print]=$2; shift 2;;
+	    -- ) shift; break;;
+	    *) break;
+	  esac
+  done
 }
+
+init $OPTS
 main.cmd "$@"
 
 exit 0;
